config/routes.rb
Ffcom::Application.routes.draw do
  resources :nodes

  apipie
  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users

  namespace :api, defaults: {format: 'json'} do
    namespace :v1, path: '1' do
      resources :nodes
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    logged_in = !user.id.nil?

    if user.has_role? :admin
      can :manage, :all
    end

    if logged_in
      can :read, :user
      can :index, :user
      can :manage, Node do |node|
        node.user_id == user.id
      end
    end
  end
end

app/models/node.rb
class Node < ActiveRecord::Base
  belongs_to :user
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/api/v1/nodes_controller.rb
class Api::V1::NodesController < NodesController
  resource_description do
    resource_id 'nodes'
    api_versions '1'
    formats ['json']
  end

  def_param_group :node do
    param :mac_address, String, 'MAC address of the node'
    param :pub_key, String, 'Public key for fastd'
  end

  before_action :set_node, only: [:show, :edit, :update, :destroy]

  # GET /api/1/nodes
  # GET /api/1/nodes.json
  api :GET, "/1/nodes", "List nodes"
  def index
    @nodes = Node.all
  end

  # GET /api/1/nodes/1
  # GET /api/1/nodes/1.json
  api :GET, "/1/nodes/:id", "Show a node"
  example 'node'
  def show
  end

  # POST /api/1/nodes
  # POST /api/1/nodes.json
  api :POST, "/1/nodes", "Create a node"
  param_group :node
  example " { 'message': 'success', 'id': 1 } "
  def create
    @node = Node.new(node_params)

    respond_to do |format|
      if @node.save
        format.json { render action: 'show', status: :created, location: @node }
      else
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_node
      @node = Node.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def node_params
      params.require(:node).permit(:mac_address, :pub_key, :user_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @nodes = Node.all.limit(10)
    @users = User.all
  end
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_node, only: [:show, :edit, :update, :destroy]

  # GET /nodes
  # GET /nodes.json
  def index
    @nodes = Node.all
  end

  # GET /nodes/1
  # GET /nodes/1.json
  def show
  end

  # GET /nodes/new
  def new
    @node = Node.new
  end

  # GET /nodes/1/edit
  def edit
    authorize! :edit, @node
  end

  # POST /nodes
  # POST /nodes.json
  def create
    @node = Node.new(node_params)

    respond_to do |format|
      if @node.save
        format.html { redirect_to @node, notice: 'Node was successfully created.' }
        format.json { render action: 'show', status: :created, location: @node }
      else
        format.html { render action: 'new' }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nodes/1
  # PATCH/PUT /nodes/1.json
  def update
    authorize! :update, @node
    respond_to do |format|
      if @node.update(node_params)
        format.html { redirect_to @node, notice: 'Node was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nodes/1
  # DELETE /nodes/1.json
  def destroy
    authorize! :delete, @node
    @node.destroy
    respond_to do |format|
      format.html { redirect_to nodes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_node
      @node = Node.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def node_params
      params.require(:node).permit(:mac_address, :pub_key, :user_id)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_filter :update_sanitized_params, if: :devise_controller?

  def update_sanitized_params
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:name, :email, :password, :password_confirmation)}
    devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:name, :email, :password, :password_confirmation, :current_password)}
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, :user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
  
  def update
    authorize! :update, current_user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user], :as => :admin)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end
    
  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end
end

app/helpers/api/v1/nodes_helper.rb
module Api::V1::NodesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/views/home/index.html.erb
<div class="row">
  <div class="col-lg-3">
    <div class="panel panel-info">
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-6">
            <i class="fa fa-arrow-circle-o-right fa-5x"></i>
          </div>
          <div class="col-xs-6 text-right">
            <p class="announcement-heading"><%= @nodes.count %></p>
            <p class="announcement-text">Nodes</p>
          </div>
        </div>
      </div>
      <a href="/nodes">
        <div class="panel-footer announcement-bottom">
          <div class="row">
            <div class="col-xs-6">
              View all Nodes
            </div>
            <div class="col-xs-6 text-right">
              <i class="fa fa-arrow-circle-right"></i>
            </div>
          </div>
        </div>
      </a>
    </div>
  </div>
  <div class="col-lg-3">
    <div class="panel panel-warning">
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-6">
            <i class="fa fa-users fa-5x"></i>
          </div>
          <div class="col-xs-6 text-right">
            <p class="announcement-heading"><%= @users.count %></p>
            <p class="announcement-text">Freifunker</p>
          </div>
        </div>
      </div>
      <a href="/users">
        <div class="panel-footer announcement-bottom">
          <div class="row">
            <div class="col-xs-6">
              View Userlist
            </div>
            <div class="col-xs-6 text-right">
              <i class="fa fa-arrow-circle-right"></i>
            </div>
          </div>
        </div>
      </a>
    </div>
  </div>
  <div class="col-lg-3">
    <div class="panel panel-danger">
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-6">
            <i class="fa fa-tasks fa-5x"></i>
          </div>
          <div class="col-xs-6 text-right">
            <p class="announcement-heading">18</p>
            <p class="announcement-text">Errors</p>
          </div>
        </div>
      </div>
      <a href="#">
        <div class="panel-footer announcement-bottom">
          <div class="row">
            <div class="col-xs-6">
              Fix Issues
            </div>
            <div class="col-xs-6 text-right">
              <i class="fa fa-arrow-circle-right"></i>
            </div>
          </div>
        </div>
      </a>
    </div>
  </div>
  <div class="col-lg-3">
    <div class="panel panel-success">
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-6">
            <i class="fa fa-comments fa-5x"></i>
          </div>
          <div class="col-xs-6 text-right">
            <p class="announcement-heading">56</p>
            <p class="announcement-text">New Orders!</p>
          </div>
        </div>
      </div>
      <a href="#">
        <div class="panel-footer announcement-bottom">
          <div class="row">
            <div class="col-xs-6">
              Complete Orders
            </div>
            <div class="col-xs-6 text-right">
              <i class="fa fa-arrow-circle-right"></i>
            </div>
          </div>
        </div>
      </a>
    </div>
  </div>
</div><!-- /.row -->

<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-bar-chart-o"></i> Traffic Statistics: October 1, 2013 - October 31, 2013</h3>
      </div>
      <div class="panel-body">
        <div id="morris-chart-area"></div>
      </div>
    </div>
  </div>
</div><!-- /.row -->

<div class="row">
  <div class="col-lg-4">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-long-arrow-right"></i> Traffic Sources: October 1, 2013 - October 31, 2013</h3>
      </div>
      <div class="panel-body">
        <div id="morris-chart-donut"></div>
        <div class="text-right">
          <a href="#">View Details <i class="fa fa-arrow-circle-right"></i></a>
        </div>
      </div>
    </div>
  </div>
  <div class="col-lg-4">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-clock-o"></i> Recent Activity</h3>
      </div>
      <div class="panel-body">
        <div class="list-group">
          <a href="#" class="list-group-item">
            <span class="badge">just now</span>
            <i class="fa fa-calendar"></i> Calendar updated
          </a>
          <a href="#" class="list-group-item">
            <span class="badge">4 minutes ago</span>
            <i class="fa fa-comment"></i> Commented on a post
          </a>
          <a href="#" class="list-group-item">
            <span class="badge">23 minutes ago</span>
            <i class="fa fa-truck"></i> Order 392 shipped
          </a>
          <a href="#" class="list-group-item">
            <span class="badge">46 minutes ago</span>
            <i class="fa fa-money"></i> Invoice 653 has been paid
          </a>
          <a href="#" class="list-group-item">
            <span class="badge">1 hour ago</span>
            <i class="fa fa-user"></i> A new user has been added
          </a>
          <a href="#" class="list-group-item">
            <span class="badge">2 hours ago</span>
            <i class="fa fa-check"></i> Completed task: "pick up dry cleaning"
          </a>
          <a href="#" class="list-group-item">
            <span class="badge">yesterday</span>
            <i class="fa fa-globe"></i> Saved the world
          </a>
          <a href="#" class="list-group-item">
            <span class="badge">two days ago</span>
            <i class="fa fa-check"></i> Completed task: "fix error on sales page"
          </a>
        </div>
        <div class="text-right">
          <a href="#">View All Activity <i class="fa fa-arrow-circle-right"></i></a>
        </div>
      </div>
    </div>
  </div>
  <div class="col-lg-4">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-money"></i> Recent Nodes</h3>
      </div>
      <div class="panel-body">
        <div class="table-responsive">
          <table class="table table-bordered table-hover table-striped tablesorter">
            <thead>
              <tr>
                <th>Node # <i class="fa fa-sort"></i></th>
                <th>MAC Address <i class="fa fa-sort"></i></th>
                <th>PubKey ID <i class="fa fa-sort"></i></th>
                <th>Owner <i class="fa fa-sort"></i></th>
              </tr>
            </thead>
            <tbody>
            <% @nodes.each do |node| %>
            <tr>
              <td><%= node.id %></td>
              <td><%= node.mac_address %></td>
              <td><%= node.pub_key %></td>
              <td><%= node.user.name rescue 'unclaimed' %></td>
            </tr>
            <% end %>
            </tbody>
          </table>
        </div>
        <div class="text-right">
          <a href="/nodes">View All Nodes <i class="fa fa-arrow-circle-right"></i></a>
        </div>
      </div>
    </div>
  </div>
</div><!-- /.row -->

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Twitter Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<!-- Brand and toggle get grouped for better mobile display -->
<div class="navbar-header">
  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
  <%= link_to "ffcom", root_path, :class => 'navbar-brand' %>
</div>

<!-- Collect the nav links, forms, and other content for toggling -->
<div class="collapse navbar-collapse navbar-ex1-collapse">
  <ul class="nav navbar-nav side-nav">
    <li class="active"><a href="/"><i class="fa fa-dashboard"></i> Dashboard</a></li>
    <li><a href="/nodes"><i class="fa fa-bar-chart-o"></i> Nodes</a></li>
    <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-caret-square-o-down"></i> Developer <b class="caret"></b></a>
    <ul class="dropdown-menu">
      <li><a href="/apipie">API Docs</a></li>
    </ul>
    </li>
  </ul>

  <ul class="nav navbar-nav navbar-right navbar-user">
    <li class="dropdown messages-dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-envelope"></i> Messages <span class="badge">7</span> <b class="caret"></b></a>
    <ul class="dropdown-menu">
      <li class="dropdown-header">7 New Messages</li>
      <li class="message-preview">
      <a href="#">
        <span class="avatar"><img src="http://placehold.it/50x50"></span>
        <span class="name">John Smith:</span>
        <span class="message">Hey there, I wanted to ask you something...</span>
        <span class="time"><i class="fa fa-clock-o"></i> 4:34 PM</span>
      </a>
      </li>
      <li class="divider"></li>
      <li class="message-preview">
      <a href="#">
        <span class="avatar"><img src="http://placehold.it/50x50"></span>
        <span class="name">John Smith:</span>
        <span class="message">Hey there, I wanted to ask you something...</span>
        <span class="time"><i class="fa fa-clock-o"></i> 4:34 PM</span>
      </a>
      </li>
      <li class="divider"></li>
      <li class="message-preview">
      <a href="#">
        <span class="avatar"><img src="http://placehold.it/50x50"></span>
        <span class="name">John Smith:</span>
        <span class="message">Hey there, I wanted to ask you something...</span>
        <span class="time"><i class="fa fa-clock-o"></i> 4:34 PM</span>
      </a>
      </li>
      <li class="divider"></li>
      <li><a href="#">View Inbox <span class="badge">7</span></a></li>
    </ul>
    </li>
    <li class="dropdown alerts-dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bell"></i> Alerts <span class="badge">3</span> <b class="caret"></b></a>
    <ul class="dropdown-menu">
      <li><a href="#">Default <span class="label label-default">Default</span></a></li>
      <li><a href="#">Primary <span class="label label-primary">Primary</span></a></li>
      <li><a href="#">Success <span class="label label-success">Success</span></a></li>
      <li><a href="#">Info <span class="label label-info">Info</span></a></li>
      <li><a href="#">Warning <span class="label label-warning">Warning</span></a></li>
      <li><a href="#">Danger <span class="label label-danger">Danger</span></a></li>
      <li class="divider"></li>
      <li><a href="#">View All</a></li>
    </ul>
    </li>
    <li class="dropdown user-dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> John Smith <b class="caret"></b></a>
    <ul class="dropdown-menu">
      <li><a href="#"><i class="fa fa-user"></i> Profile</a></li>
      <li><a href="#"><i class="fa fa-envelope"></i> Inbox <span class="badge">7</span></a></li>
      <li><a href="#"><i class="fa fa-gear"></i> Settings</a></li>
      <li class="divider"></li>
      <li><a href="#"><i class="fa fa-power-off"></i> Log Out</a></li>
    </ul>
    </li>
  </ul>
</div><!-- /.navbar-collapse -->

<!--
<%= link_to "Home", root_path, :class => 'brand' %>
<ul class="nav">
  <% if user_signed_in? %>
    <li>
  <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>
  </li>
<% else %>
    <li>
  <%= link_to 'Login', new_user_session_path %>
  </li>
<% end %>
  <% if user_signed_in? %>
    <li>
  <%= link_to 'Edit account', edit_user_registration_path %>
  </li>
  <% if current_user.has_role? :admin %>
    <li>
  <%= link_to 'Admin', users_path %>
  </li>
<% end %>
<% else %>
    <li>
  <%= link_to 'Sign up', new_user_registration_path %>
  </li>
<% end %>
</ul>
-->

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/_page_header.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1>Dashboard <small>Statistics Overview</small></h1>
    <ol class="breadcrumb">
      <li class="active"><i class="fa fa-dashboard"></i> Dashboard</li>
    </ol>
    <%= render partial: 'layouts/messages' %>
  </div>
</div><!-- /.row -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Dashboard - SB Admin</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Ffcom" %>">
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <div id="wrapper">

      <!-- Sidebar -->
      <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <%= render partial: 'layouts/navigation' %>
      </nav>

      <div id="page-wrapper">
        <%= render partial: 'layouts/page_header' %>
        <%= yield %>
      </div><!-- /#page-wrapper -->

    </div><!-- /#wrapper -->
  </body>
</html>

app/views/nodes/_form.html.erb
<%= simple_form_for(@node) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :mac_address %>
    <%= f.input :pub_key %>
    <%= f.association :user %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/nodes/edit.html.erb
<h1>Editing node</h1>

<%= render 'form' %>

<%= link_to 'Show', @node %> |
<%= link_to 'Back', nodes_path %>

app/views/nodes/index.html.erb
<h1>Listing nodes</h1>

<table>
  <thead>
    <tr>
      <th>Mac address</th>
      <th>Pub key</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @nodes.each do |node| %>
      <tr>
        <td><%= node.mac_address %></td>
        <td><%= node.pub_key %></td>
        <td><%= node.user %></td>
        <td><%= link_to 'Show', node %></td>
        <td><%= link_to 'Edit', edit_node_path(node) %></td>
        <td><%= link_to 'Destroy', node, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Node', new_node_path %>

app/views/nodes/new.html.erb
<h1>New node</h1>

<%= render 'form' %>

<%= link_to 'Back', nodes_path %>

app/views/nodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Mac address:</strong>
  <%= @node.mac_address %>
</p>

<p>
  <strong>Pub key:</strong>
  <%= @node.pub_key %>
</p>

<p>
  <strong>User:</strong>
  <%= @node.user %>
</p>

<%= link_to 'Edit', edit_node_path(@node) %> |
<%= link_to 'Back', nodes_path %>

app/views/users/_user.html.erb
<div id="role-options-<%= user.id %>" class="modal" style="display: none;">
  <%= simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f| %>
    <div class="modal-header">
      <a class="close" data-dismiss="modal">&#215;</a>
      <h3>Change Role</h3>
    </div>
    <div class="modal-body">
      <%= f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline', checked: user.role_ids.first %>
    </div>
    <div class="modal-footer">
      <%= f.submit "Change Role", :class => "btn" %>
      <a class="btn" data-dismiss="modal" href="#">Close</a>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<h3>Users</h3>
<div class="span8">
<table class="table table-condensed">
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Registered</th>
      <th>Role</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.name, user %></td>
      <td><%= user.email %></td>
      <td><%= user.created_at.to_date %></td>
      <td><%= user.roles.first.name.titleize unless user.roles.first.nil? %></td>
      <td>
        <a data-toggle="modal" href="#role-options-<%= user.id %>" class="btn btn-mini" type="button">Change role</a>
        <%= render user %>
      </td>
      <td><%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user %></td>
    </tr>
  <% end %>
  </tbody>
</table>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>User: <%= @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>